version: "3"
services:
  go-crud:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_USERS_DATABASE: users
      JWT_SECRET: secrettt
      MONGO_USERS_COLLECTION: users
    ports:
      - "8080:8080"
    depends_on:
     - mongodb
    networks:
     - gocrud_network
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    networks:
     - gocrud_network

networks:
  gocrud_network: